/*
====================================================
Magnitude Analysis
====================================================
Purppose:
	- To qualify data and group by specific dimension
	- To understand data distribution across categories

SQL Func:
	- Aggregate Function: SUM(), COUNT(), AVG()
	- GROUP BY, ORDER BY

=====================================================
*/

-- Find total customers by countries
select
	country
	, count(customer_key) as customerByCountry
from gold.dim_customers
group by country
order by count(customer_key) desc;


-- Find total customers by gender
select 
	gender
	, count(customer_key) customerByGender
from gold.dim_customers
group by gender
order by count(customer_key) desc;


-- Find total products by category
select 
	category
	, count(product_key) as totalProductByCategory
from gold.dim_products
group by category
order by count(product_key) desc;

-- What is the average costs in each category?
select
	category
	, avg(cost) as avgCostByCategory
from gold.dim_products
group by category
order by avg(cost) desc;


-- What is the total revenue generated for each category?

select
	p.category
	, sum(s.sales_amount) as totalRevenueByCategory
from gold.fact_sales s
left join gold.dim_products p
	on p.product_key = s.product_key
group by p.category
order by sum(s.sales_amount) desc;



-- What is the total revenue generated by each customer?
select 
	c.customer_key
	, c.first_name
	, c.last_name
	, sum(s.sales_amount) as revenueByCustomer
from gold.fact_sales s
left join gold.dim_customers c
	on s.customer_key = c.customer_key
group by c.customer_key, c.first_name, c.last_name
order by sum(s.sales_amount) desc;


-- What is the distribution of sold items across countries?

select 
	c.country
	, sum(quantity) as soldItemByCountry
from gold.fact_sales s
left join gold.dim_customers c
	on s.customer_key = c.customer_key
group by c.country
order by soldItemByCountry desc;
